"""added context along with QA pair response

Revision ID: 1c771c4b4131
Revises: 84a36bf322ae
Create Date: 2026-05-12 16:33:17.635397

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1c771c4b4131'
down_revision: Union[str, Sequence[str], None] = '84a36bf322ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('qa_items', sa.Column('context', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('qa_items', 'context')
    # ### end Alembic commands ###
