"""added mising core fields from QA item

Revision ID: 367b20d536e7
Revises: 2cc17fa6ab25
Create Date: 2026-04-11 16:41:09.813571

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '367b20d536e7'
down_revision: Union[str, Sequence[str], None] = '2cc17fa6ab25'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('qa_items', sa.Column('next_review', sa.Integer(), nullable=False))
    op.add_column('qa_items', sa.Column('current_step_index', sa.Integer(), nullable=False))
    op.add_column('qa_items', sa.Column('ease_factor', sa.Float(), nullable=False))
    op.add_column('qa_items', sa.Column('interval', sa.Integer(), nullable=False))
    op.add_column('qa_items', sa.Column('phase', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('qa_items', 'phase')
    op.drop_column('qa_items', 'interval')
    op.drop_column('qa_items', 'ease_factor')
    op.drop_column('qa_items', 'current_step_index')
    op.drop_column('qa_items', 'next_review')
    # ### end Alembic commands ###
