"""added review session model as logs

Revision ID: 506ba2678f39
Revises: 367b20d536e7
Create Date: 2026-04-26 11:19:17.312848

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '506ba2678f39'
down_revision: Union[str, Sequence[str], None] = '367b20d536e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('review_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('start_review', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('end_review', sa.DateTime(), nullable=False),
    sa.Column('graduated_cards', sa.Integer(), nullable=False),
    sa.Column('learning_cards', sa.Integer(), nullable=False),
    sa.Column('relearning_cards', sa.Integer(), nullable=False),
    sa.Column('new_cards', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('review_sessions')
    # ### end Alembic commands ###
