"""updated the DATETIME of review session to timezone aware

Revision ID: 84a36bf322ae
Revises: e739a674cf2a
Create Date: 2026-04-27 01:04:20.887759

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '84a36bf322ae'
down_revision: Union[str, Sequence[str], None] = 'e739a674cf2a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "review_sessions",
        "start_review",
        type = sa.DateTime(timezone=True),
        existing_type= sa.DateTime(timezone=False),
        existing_nullable=False
    )
    op.alter_column(
        "review_sessions",
        "end_review",
        type = sa.DateTime(timezone=True),
        existing_type= sa.DateTime(timezone=False),
        existing_nullable=False
    )
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
